name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup show

      - name: Check code format
        run: cargo fmt --check

      - name: Build
        run: cargo build --release --target x86_64-unknown-uefi

      - name: Doc
        run: cargo doc --target x86_64-unknown-uefi

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup show

      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-system-x86

      - name: Run end-to-end test
        run: ./example-kernel/test.sh
